# Full reference
# https://onbjerg.github.io/foundry-book/reference/config.html

[profile.default]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 20_000
gas_reports = ["*"]
via_ir = true

[profile.ci]
verbosity = 4
